### PR TITLE
ode: support Fedora's wrong libname

### PR DESCRIPTION
**Pull request by mathstuf**
Fedora [screwed up](https://bugzilla.redhat.com/show_bug.cgi?id=1204547) here. May as well attempt to help.

### CODE REVIEW

**Comment by mathstuf** [comment]
So it seems ODE itself just always builds `libode.so.X`. Where did the existing `libode_double` names come from?

**Comment by aldacron** [comment]
Thanks!
The lib names are what remains of the original binding contributed to Derelict 1 by a guy named Eric Poggel (JoeCoder) several years ago. I assume he was primarily a Windows user, like me. On Windows, ODE build ode_double.dll and ode_single.dll, with the accompanying import libs of the same name. Using MinGW, the import libs have the format libode_double.a. Probably he just used the same format without ever testing it on Linux. Looking at the original binding, the libode form wasn't even present. When I rewrote the binding from scratch for Derelict 3, I kept the library names and only tested loading on Windows.

**Comment by mathstuf** [comment]
I presume the libnames come from premake?

**Comment by aldacron** [comment]
Yep:
```Lua
configuration { "Debug" }
      targetname "oded"
	  
    configuration { "Release" }
      targetname "ode"
	  
    configuration { "DebugSingle*" }
      targetname "ode_singled"
      
    configuration { "ReleaseSingle*" }
      targetname "ode_single"
      
    configuration { "DebugDouble*" }
      targetname "ode_doubled"
      
    configuration { "ReleaseDouble*" }
      targetname "ode_double"
```

**Pull request merged**
